import { useState, useEffect } from "react";
import { Loader, Card, FormField } from "../components";

const Home = () => {
  const [loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState(null);


  return(
  <section className="max-w-7xl mx-auto">
    <div>
      <h1 className="font-extrabold text-[#222328] text-[32px]">ALX Portfolio Project</h1>
      <p className="mt-2 text-[#666e75] text-[16px] max-w-[500px]">Browse through a collection of breathing-taking and stunning images generated by AI</p>
    </div>

  </section>
  )
};

export default Home;
